### ISSUE TITLE
Stop Script

### ISSUE THREAD

**Issue by mjack24** [Johnson468/Stay-Awake#1] opened 2019-05-11 16:18 UTC
How do I get this to stop after starting it?

**Comment by joseph-lister** [comment] 2020-04-27 15:42
ctrl + C will stop the python script running

**Comment by ojoksimovic** [comment] 2020-11-04 18:05
press the shift key.

**Comment by GavinChris7** [comment] 2021-04-27 17:16
not working

**Comment by GavinChris7** [comment] 2021-04-27 17:16
when run pycharm

**Comment by AntonioJPE** [comment] 2023-03-27 14:40
> ctrl + C will stop the python script running

If the issue is solved we can close it, no?

**Comment by joseph-lister** [comment] 2023-03-28 03:21
Yes please close Sent from my iPhoneOn 27 Mar 2023, at 22:40, AntonioJPE ***@***.***> wrote:﻿

ctrl + C will stop the python script running

If the issue is solved we can close it, no?

**Closed as completed** 2024-07-31 02:47 UTC
